
export const  LANGUAGES = [
  {
  language: "english",
  code:"en",
  ID:1
  
  },
  {
    language: "chinese",
    code:"zh",
     ID:2
  },
    {language: "german",
    code:"de",
    ID:3,},
  {
    language: "spanish",
    code:"es",
    ID:4},
  {language: "russian",
  code:"ru",
  ID:5},
  {language: "korean",
  code:"ko",
  ID:6},
  {language: "french",
  code:"fr",
  ID:7},
  {language: "japanese",
  code:"ja",
  ID:8},
  {language: "portuguese",code:"pt",ID:9},
  {language: "turkish",code:"tr",ID:10},
  {language: "polish",code:"pl",ID:11},
  {language: "catalan",code:"ca",ID:12},
 { language: "dutch",code:"nl",ID:13},
  {language: "arabic",code:"ar",ID:14},
  {language: "swedish",code:"sv",ID:15},
  {language: "italian",code:"it",ID:16},
  {language: "indonesian",code:"id",ID:17},
  {language: "hindi",code:"hi",ID:18},
  {language: "finnish",code:"fi",ID:19},
 { language: "vietnamese",code:"vi",ID:20},
  {language: "hebrew",code:"he",ID:21},
  {language: "ukrainian",code:"uk",ID:22},
  {language: "greek",code:"el",ID:23},
  {language: "malay",code:"ms",ID:24},
  {language: "czech",code:"cs",ID:25},
  {language: "romanian",code:"ro",ID:26},
  {language: "danish",code:"da",ID:27},
  {language: "hungarian",code:"hu",ID:28},
 { language: "tamil",code:"ta",ID:29},
  {language: "norwegian",code:"no",ID:30},
  {language: "thai",code:"th",ID:31},
  {language: "urdu",code:"ur",ID:32},
  {language: "croatian",code:"hr",ID:33},
  {language: "bulgarian",code:"bg",ID:34},
  {language: "lithuanian",code:"lt",ID:35},
  {language: "latin",code:"la",ID:36},
  {language: "maori",code:"mi",ID:37},
  {language: "malayalam",code:"ml",ID:38},
  {language: "welsh",code:"cy",ID:39},
  {language: "slovak",code:"sk",ID:40},
 { language: "telugu",code:"te",ID:41},
  {language: "persian",code:"fa",ID:42},
  {language: "latvian",code:"lv",ID:43},
 { language: "bengali",code:"bn",ID:44},
  {language: "serbian",code:"sr",ID:45},
  {"az": "azerbaijani",ID:46},
  {"sl": "slovenian",ID:47},
  {"kn": "kannada",ID:47},
  {"et": "estonian",ID:48},
  {"mk": "macedonian",ID:49},
  {"br": "breton",ID:50},
  {"eu": "basque",ID:51},
  {"is": "icelandic",ID:52},
  {"hy": "armenian",ID:53},
  {"ne": "nepali",ID:54},
 { "mn": "mongolian",ID:55},
  {"bs": "bosnian",ID:56},
  {"kk": "kazakh",ID:57},
  {"sq": "albanian",ID:58},
  {"sw": "swahili",ID:59},
 { "gl": "galician",ID:60},
  {"mr": "marathi",ID:61},
  {"pa": "punjabi",ID:62},
  {"si": "sinhala",ID:63},
  {"km": "khmer",ID:64},
  {"sn": "shona",ID:65},
  {"yo": "yoruba",ID:66},
  {"yo": "yoruba",ID:67},
  {"yo": "yoruba",ID:68},
  {"so": "somali",ID:69},
  {"af": "afrikaans",ID:70},
 { "oc": "occitan",ID:71},
 { "ka": "georgian",ID:72},
  {"be": "belarusian",ID:73},
  {"tg": "tajik",ID:74},
  {"sd": "sindhi",ID:75},
  {"gu": "gujarati",ID:76},
  {"am": "amharic",ID:77},
  {"yi": "yIDdish",ID:78},
  {"lo": "lao",ID:79},
  {"uz": "uzbek",ID:80},
  {"fo": "faroese",ID:81},
  {"ht": "haitian creole",ID:82},
 { "ps": "pashto",ID:83},
  {"tk": "turkmen",ID:84},
  {"nn": "nynorsk",ID:85},
  {"mt": "maltese",ID:86},
  {"sa": "sanskrit",ID:87},
  {"lb": "luxembourgish",ID:88},
  {"my": "myanmar",ID:89},
  {"bo": "tibetan",ID:90},
 { "tl": "tagalog",ID:91},
  {"mg": "malagasy",ID:92},
  {"as": "assamese",ID:93},
 { "tt": "tatar",ID:94},
  {"haw": "hawaiian",ID:95},
  {"ln": "lingala",ID:96},
  {"ha": "hausa",ID:97},
 { "ba": "bashkir",ID:98},
 { "jw": "javanese",ID:99},
  {"su": "sundanese",ID:100}
]