
export const  LANGUAGES = [
  {
  "en": "english",
  ID:1
  
  },
  {
    "zh": "chinese",
     ID:2
  },
  {"de": "german",ID:3},
  {"es": "spanish",ID:4},
  {"ru": "russian",ID:5},
  {"ko": "korean",ID:6},
  {"fr": "french",ID:7},
  {"ja": "japanese",ID:8},
  {"pt": "portuguese",ID:9},
  {"tr": "turkish",ID:10},
  {"pl": "polish",ID:11},
  {"ca": "catalan",ID:12},
 { "nl": "dutch",ID:13},
  {"ar": "arabic",ID:14},
  {"sv": "swedish",ID:15},
  {"it": "italian",ID:16},
  {"id": "indonesian",ID:17},
  {"hi": "hindi",ID:18},
  {"fi": "finnish",ID:19},
 { "vi": "vietnamese",ID:20},
  {"he": "hebrew",ID:21},
  {"uk": "ukrainian",ID:22},
  {"el": "greek",ID:23},
  {"ms": "malay",ID:24},
  {"cs": "czech",ID:25},
  {"ro": "romanian",ID:26},
  {"da": "danish",ID:27},
  {"hu": "hungarian",ID:28},
 { "ta": "tamil",ID:29},
  {"no": "norwegian",ID:30},
  {"th": "thai",ID:31},
  {"ur": "urdu",ID:32},
  {"hr": "croatian",ID:33},
  {"bg": "bulgarian",ID:34},
  {"lt": "lithuanian",ID:35},
  {"la": "latin",ID:36},
  {"mi": "maori",ID:37},
  {"ml": "malayalam",ID:38},
  {"cy": "welsh",ID:39},
  {"sk": "slovak",ID:40},
 { "te": "telugu",ID:41},
  {"fa": "persian",ID:42},
  {"lv": "latvian",ID:43},
 { "bn": "bengali",ID:44},
  {"sr": "serbian",ID:45},
  {"az": "azerbaijani",ID:46},
  {"sl": "slovenian",ID:47},
  {"kn": "kannada",ID:47},
  {"et": "estonian",ID:48},
  {"mk": "macedonian",ID:49},
  {"br": "breton",ID:50},
  {"eu": "basque",ID:51},
  {"is": "icelandic",ID:52},
  {"hy": "armenian",ID:53},
  {"ne": "nepali",ID:54},
 { "mn": "mongolian",ID:55},
  {"bs": "bosnian",ID:56},
  {"kk": "kazakh",ID:57},
  {"sq": "albanian",ID:58},
  {"sw": "swahili",ID:59},
 { "gl": "galician",ID:60},
  {"mr": "marathi",ID:61},
  {"pa": "punjabi",ID:62},
  {"si": "sinhala",ID:63},
  {"km": "khmer",ID:64},
  {"sn": "shona",ID:65},
  {"yo": "yoruba",ID:66},
  {"yo": "yoruba",ID:67},
  {"yo": "yoruba",ID:68},
  {"so": "somali",ID:69},
  {"af": "afrikaans",ID:70},
 { "oc": "occitan",ID:71},
 { "ka": "georgian",ID:72},
  {"be": "belarusian",ID:73},
  {"tg": "tajik",ID:74},
  {"sd": "sindhi",ID:75},
  {"gu": "gujarati",ID:76},
  {"am": "amharic",ID:77},
  {"yi": "yIDdish",ID:78},
  {"lo": "lao",ID:79},
  {"uz": "uzbek",ID:80},
  {"fo": "faroese",ID:81},
  {"ht": "haitian creole",ID:82},
 { "ps": "pashto",ID:83},
  {"tk": "turkmen",ID:84},
  {"nn": "nynorsk",ID:85},
  {"mt": "maltese",ID:86},
  {"sa": "sanskrit",ID:87},
  {"lb": "luxembourgish",ID:88},
  {"my": "myanmar",ID:89},
  {"bo": "tibetan",ID:90},
 { "tl": "tagalog",ID:91},
  {"mg": "malagasy",ID:92},
  {"as": "assamese",ID:93},
 { "tt": "tatar",ID:94},
  {"haw": "hawaiian",ID:95},
  {"ln": "lingala",ID:96},
  {"ha": "hausa",ID:97},
 { "ba": "bashkir",ID:98},
 { "jw": "javanese",ID:99},
  {"su": "sundanese",ID:100}
]